import {sqliteTable,text,integer,uniqueIndex,index} from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{id:text('id').primaryKey(),name:text('name').notNull(),created:text('created').notNull()});
export const places=sqliteTable('places',{id:text('id').primaryKey(),payload:text('payload').notNull(),status:text('status').notNull().default('pending'),version:integer('version').notNull().default(1),created:text('created').notNull(),receipt:text('receipt'),requestKey:text('request_key'),ownerId:text('owner_id')},t=>[uniqueIndex('places_receipt_unique').on(t.receipt),uniqueIndex('places_request_unique').on(t.requestKey),index('places_status').on(t.status)]);
export const reviews=sqliteTable('reviews',{id:text('id').primaryKey(),placeId:text('place_id').notNull().references(()=>places.id),userId:text('user_id').notNull().references(()=>users.id),parentId:text('parent_id'),payload:text('payload').notNull(),status:text('status').notNull().default('pending'),version:integer('version').notNull().default(1),requestKey:text('request_key').notNull(),created:text('created').notNull()},t=>[uniqueIndex('reviews_request_unique').on(t.requestKey),index('reviews_place_status').on(t.placeId,t.status),index('reviews_user').on(t.userId)]);
export const photos=sqliteTable('photos',{id:text('id').primaryKey(),placeId:text('place_id').notNull().references(()=>places.id),reviewId:text('review_id').references(()=>reviews.id),storageKey:text('storage_key').notNull(),metadata:text('metadata').notNull(),size:integer('size').notNull(),created:text('created').notNull()},t=>[index('photos_place').on(t.placeId),index('photos_review').on(t.reviewId)]);
export const reports=sqliteTable('reports',{id:text('id').primaryKey(),placeId:text('place_id').notNull().references(()=>places.id),reason:text('reason').notNull(),status:text('status').notNull().default('pending'),version:integer('version').notNull().default(1),created:text('created').notNull()});
export const moderation=sqliteTable('moderation_events',{id:text('id').primaryKey(),recordType:text('record_type').notNull(),recordId:text('record_id').notNull(),actor:text('actor').notNull(),status:text('status').notNull(),reason:text('reason').notNull(),internalNote:text('internal_note').notNull(),created:text('created').notNull()},t=>[index('moderation_record').on(t.recordType,t.recordId)]);
export const revisions=sqliteTable('place_revisions',{id:text('id').primaryKey(),placeId:text('place_id').notNull().references(()=>places.id),version:integer('version').notNull(),before:text('before_payload').notNull(),after:text('after_payload').notNull(),actor:text('actor').notNull(),reason:text('reason').notNull(),created:text('created').notNull()},t=>[uniqueIndex('revision_place_version').on(t.placeId,t.version)]);
export const limits=sqliteTable('rate_limits',{id:text('id').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()},t=>[index('rate_expiry').on(t.expires)]);
