import React,{useEffect,useState} from 'react';
import Select from './Select.jsx';
export default function AdminAccounts({api,notify}) {
 const [users,setUsers]=useState(null),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[reasons,setReasons]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 async function load(){setLoading(true);try{setUsers(await api('/admin/accounts'));setError('');}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 async function update(user){setBusy(true);setError('');try{const account=await api('/admin/accounts/'+encodeURIComponent(user.id),{method:'POST',body:{status:user.account.status==='muted'?'active':'muted',reason:reasons[user.id],version:user.account.version}});setUsers(old=>old.map(u=>u.id===user.id?{...u,account}:u));setReasons(old=>({...old,[user.id]:''}));notify(account.status==='muted'?'已限制该账号发布内容':'已恢复该账号发布权限');}catch(e){setError(e.message);}finally{setBusy(false);}}
 const visible=users?.filter(u=>(filter==='all'||u.account.status===filter)&&u.name.toLowerCase().includes(query.trim().toLowerCase()))||[];
 return <section className="admin-accounts"><p className="muted">显示最近注册的最多 500 个本站账号。禁言即时作用于已有登录会话，保留浏览和申诉权限；处理原因向本人展示。</p><div className="admin-filters"><label>账号状态<Select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部账号</option><option value="active">可正常使用</option><option value="muted">已禁言</option></Select></label><label>搜索用户名<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="输入公开用户名"/></label><button disabled={loading||busy} onClick={load}>{loading?'正在刷新…':'刷新账号'}</button></div>{error&&<p className="error" role="alert">{error}</p>}{!users?<p role="status">{loading?'正在加载账号…':'账号加载失败，可点击刷新重试。'}</p>:!visible.length?<p className="empty">当前条件下没有账号。</p>:visible.map(u=><article className="admin-row" key={u.id}><div className="admin-record"><span className="status">{u.role==='admin'?'管理员':u.account.status==='muted'?'已禁言':'正常'}</span><h3>{u.name}</h3><p className="muted">{new Date(u.created).toLocaleDateString('zh-CN')} 注册 · {u.account.policyAccepted?'已确认当前协议':'发言前待确认协议'}</p>{u.account.reason&&<p>最近处理说明：{u.account.reason}</p>}</div>{u.role!=='admin'&&<div className="admin-actions"><label className="wizard-field">处理原因 · 向本人展示<textarea maxLength={600} value={reasons[u.id]||''} onChange={e=>setReasons(old=>({...old,[u.id]:e.target.value}))} placeholder="填写 3–600 字的事实依据或恢复原因"/></label><button className={u.account.status==='muted'?'primary':'outline'} disabled={busy||(reasons[u.id]||'').trim().length<3} onClick={()=>update(u)}>{busy?'正在处理…':u.account.status==='muted'?'恢复发布权限':'限制发布权限'}</button></div>}</article>)}</section>;
}
