import AdminEditor from './AdminEditor.jsx';
import AdminHistory from './AdminHistory.jsx';
import Select from './Select.jsx';
import React,{useEffect,useState} from 'react';
import SubmissionPreview from './SubmissionPreview.jsx';
const statusNames={pending:'待审核',approved:'已公开',rejected:'已拒绝 / 下架',resolved:'已处理'};
const tabs={places:'地点投稿',reviews:'评价审核',reports:'举报纠错'};
export default function AdminDesk({user,api,notify,refresh,onAdd,onOpen}){
 const [data,setData]=useState(null),[tab,setTab]=useState('places'),[status,setStatus]=useState('pending'),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[expanded,setExpanded]=useState(null),[editing,setEditing]=useState(null),[notes,setNotes]=useState({});
 async function load(){setLoading(true);try{const next=await api('/admin');setData(next);setError('');return true;}catch(e){setError(e.message);return false;}finally{setLoading(false);}}
 useEffect(()=>{if(user?.role==='admin')load();},[user?.id]);
 async function act(record,nextStatus){
  const type=tab;setBusy(true);setError('');
  try{const result=await api(`/admin/${type}/${encodeURIComponent(record.id)}`,{method:'POST',body:{status:nextStatus,version:record.version,reason:notes[record.id]?.reason||'',internalNote:notes[record.id]?.internalNote||''}});setData(old=>({...old,[type]:old[type].map(r=>r.id===record.id?{...r,status:nextStatus,version:result.version??r.version}:r)}));notify('已更新为'+statusNames[nextStatus]);await refresh();}
  catch(e){setError(e.message);}finally{setBusy(false);}
 }
 if(user?.role!=='admin')return <main className="empty">请使用管理员账号登录。</main>;
 const records=data?.[tab]||[];
 const placeFor=r=>data?.places.find(p=>p.id===r.place_id);
 const filtered=records.filter(r=>(status==='all'||r.status===status)&&[r.name,r.description,r.text,r.reason,r.address,placeFor(r)?.name].filter(Boolean).join(' ').toLowerCase().includes(query.trim().toLowerCase()));
 return <main className="admin-desk"><div className="section-heading"><div><div className="eyebrow">COMMUNITY DESK</div><h2>认真对待每一份分享。</h2></div><button className="primary" onClick={onAdd}>添加厕所</button></div>
 <div className="tabs" role="group" aria-label="审核类型">{Object.entries(tabs).map(([key,label])=><button disabled={busy} key={key} className={tab===key?'selected':''} aria-pressed={tab===key} onClick={()=>{setTab(key);setStatus('pending');setExpanded(null);setQuery('');}}>{label} · {data?.[key]?.filter(r=>r.status==='pending').length||0}</button>)}</div>
 <div className="admin-filters"><label>处理状态<Select aria-label="处理状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">待审核</option><option value="all">全部状态</option>{(tab==='reports'?['resolved']:['approved','rejected']).map(s=><option key={s} value={s}>{statusNames[s]}</option>)}</Select></label><label>搜索内容<input value={query} placeholder="地点名、地址、评价或举报内容" onChange={e=>setQuery(e.target.value)}/></label><button disabled={busy||loading} onClick={load}>{loading?'刷新中…':'刷新列表'}</button></div>
 {error&&<div className="notice" role="alert">{error}<button disabled={loading} onClick={load}>重试加载</button></div>}
 {!data?<p role="status">{loading?'正在加载审核内容…':'未能加载，请重试。'}</p>:<><p className="muted" role="status">显示 {filtered.length} / {records.length} 条{status!=='all'?` · ${statusNames[status]}`:''}</p>{!filtered.length&&<div className="empty"><h3>当前条件下没有内容</h3><p>可切换处理状态查看已处理记录。</p><button onClick={()=>{setStatus('all');setQuery('');}}>查看全部记录</button></div>}
 {filtered.map(r=><article className="admin-row" key={r.id}><div className="admin-record"><span className="status">{statusNames[r.status]||r.status}</span><h3>{tab==='places'?r.name:placeFor(r)?.name||'关联地点暂不可用'}</h3>
 {tab==='places'?<><p>{r.address}</p><p>{r.template==='source'?'公开资料收录':'实地分享'} · {r.photos?.length||0} 张投稿照片{r.imageCredit?' · 含开放许可资料图':''}</p>{r.customRegion&&<p className="notice">待规范地区：{r.customRegion}。当前不可直接发布。</p>}<button className="outline" aria-expanded={expanded===r.id} onClick={()=>setExpanded(expanded===r.id?null:r.id)}>{expanded===r.id?'收起审核资料':'展开完整审核资料'}</button>
 {expanded===r.id&&<div className="admin-preview"><div className="admin-edit-toolbar"><button className="outline" disabled={busy} onClick={()=>setEditing(editing===r.id?null:r.id)}>{editing===r.id?'关闭编辑':'修正资料'}</button></div>{editing===r.id?<AdminEditor key={r.version} place={r} api={api} onCancel={()=>setEditing(null)} onSaved={async()=>{setEditing(null);await load();await refresh();notify('修订已保存');}}/>:<SubmissionPreview place={r} photos={(r.photos||[]).map(p=>({...p,url:`/api/photos/${p.id}`}))}/>}{r.imageCredit&&<figure><img className="admin-source-image" src={r.image} alt={r.imageCredit.caption}/><figcaption>摄影：{r.imageCredit.author} · <a href={r.imageCredit.url} target="_blank" rel="noreferrer">原始来源</a> · <a href={r.imageCredit.licenseUrl} target="_blank" rel="noreferrer">{r.imageCredit.license}</a></figcaption></figure>}<AdminHistory key={r.version} id={r.id} api={api}/></div>}</>:<><p className="admin-text">{tab==='reviews'?r.text:r.reason}</p>{tab==='reviews'&&<p>到访 {r.date} · 风景 {r.scenery} / 卫生 {r.cleanliness} / 到达 {r.access} / 设施 {r.facilities}</p>}{placeFor(r)?.status==='approved'&&<button className="outline" onClick={()=>onOpen(placeFor(r))}>查看关联地点</button>}{tab==='reports'&&<p className="muted">确认核实并完成必要处理后，再标记已处理。</p>}</>}
 </div><div className="admin-actions"><label className="wizard-field">公开处理说明 · 必填<textarea maxLength={1200} placeholder="向投稿者说明处理结果与原因" value={notes[r.id]?.reason||''} onChange={e=>setNotes(n=>({...n,[r.id]:{...n[r.id],reason:e.target.value}}))}/></label><label className="wizard-field">内部备注 · 不公开<textarea maxLength={2000} placeholder="核查依据、处理记录（选填）" value={notes[r.id]?.internalNote||''} onChange={e=>setNotes(n=>({...n,[r.id]:{...n[r.id],internalNote:e.target.value}}))}/></label>{tab==='reports'?<button className="outline" disabled={busy||editing===r.id||(notes[r.id]?.reason||'').trim().length<3||r.status==='resolved'} onClick={()=>act(r,'resolved')}>标记已处理</button>:<><button className="primary" disabled={busy||editing===r.id||(notes[r.id]?.reason||'').trim().length<3||r.status==='approved'||(tab==='places'&&(expanded!==r.id||!!r.customRegion))} onClick={()=>act(r,'approved')}>审核通过</button><button className="outline" disabled={busy||editing===r.id||(notes[r.id]?.reason||'').trim().length<3||r.status==='rejected'} onClick={()=>act(r,'rejected')}>{r.status==='approved'?'下架':'拒绝'}</button>{tab==='places'&&expanded!==r.id&&r.status!=='approved'&&<small>展开并核对完整资料后可通过。</small>}</>}</div></article>)}</>}
 </main>;
}
