import React,{useMemo,useState} from 'react';
import collection from './data/editorial-places.json';
export default function EditorialPlaces(){
 const [mode,setMode]=useState('top'),[city,setCity]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1);
 const cities=useMemo(()=>[...new Set(collection.records.map(r=>r.city))].sort((a,b)=>a.localeCompare(b,'zh')),[]);
 const filtered=collection.records.filter(r=>(mode!=='top'||r.rank)&&(!city||r.city===city)&&`${r.name} ${r.city} ${r.feature} ${r.address}`.includes(query.trim())).sort((a,b)=>mode==='top'?a.rank-b.rank:b.editorial.score-a.editorial.score||a.id.localeCompare(b.id));
 const pages=Math.max(1,Math.ceil(filtered.length/12)),current=Math.min(page,pages),visible=filtered.slice((current-1)*12,current*12);
 const change=(setter,value)=>{setter(value);setPage(1)};
 return <main className="editorial-page"><div className="editorial-intro"><p className="editorial-kicker">必拉榜 / 公开资料整理</p><h1>一座城，<br/>一个值得停留的地方。</h1><p>从街巷、山野到景区和酒店，沿着设计与风景，找一处特别的厕所。</p><div className="editorial-stats"><span><b>30</b> 城推荐榜单</span><span><b>{collection.records.length}</b> 处资料</span><span><b>{cities.length}</b> 个城市 / 自治州</span></div><details><summary>这些分数怎么来？</summary><p>编辑推荐分（100分）＝设计特色35＋环境景观30＋到访便利20＋资料支撑15。基于公开资料主观评估，不代表用户评分或现场体验，不评价当前卫生、气味与排队。先选每城一处，再保留前30；不是全国普查。</p><p>整理日期 {collection.asOf}。每处提供原始图文或视频入口；目前未取得本站转载授权的照片不在本站展示。当前开放情况以现场为准。</p></details></div><div className="editorial-filters"><div role="group" aria-label="推荐范围"><button aria-pressed={mode==='top'} onClick={()=>change(setMode,'top')}>一城一厕 TOP30</button><button aria-pressed={mode==='all'} onClick={()=>change(setMode,'all')}>全部资料 · 84</button></div><input aria-label="搜索推荐资料" placeholder="搜索城市、名称或景区" value={query} onChange={e=>change(setQuery,e.target.value)}/><select aria-label="推荐城市" value={city} onChange={e=>change(setCity,e.target.value)}><option value="">全部城市</option>{cities.map(c=><option key={c}>{c}</option>)}</select></div><p className="editorial-count">找到 {filtered.length} 处 · 第 {current} / {pages} 页</p><section className="editorial-list">{visible.map(r=><article key={r.id}><div className="editorial-number">{r.rank?String(r.rank).padStart(2,'0'):'—'}<small>{r.rank?'城市推荐':'资料收录'}</small></div><div className="editorial-copy"><p className="editorial-kicker">{r.displayCity} · {r.category||'特色厕所'}</p><h2>{r.name}</h2><p>{r.feature}</p><p className="editorial-address">{r.address}</p><details><summary>到访提示与评分依据</summary><p>{r.access}</p>{r.sourceAgeDays>730&&<p>主资料已超过两年，现状需重新确认。</p>}<p>设计 {r.editorial.components.design}/35 · 景观 {r.editorial.components.setting}/30 · 便利 {r.editorial.components.access}/20 · 资料 {r.editorial.components.evidence}/15</p><p>原文日期：{r.publishedAt||'未注明'} · 暂无可核验用户评分</p><a href={r.sourceUrl} target="_blank" rel="noopener noreferrer">查看事实来源 ↗</a></details></div><div className="editorial-action"><strong>{r.editorial.score}<small>/100</small></strong><span>编辑推荐分</span><a href={r.mediaSourceUrl} target="_blank" rel="noopener noreferrer">{r.mediaType==='video'?'查看原始视频':'查看原始图文'} ↗</a></div></article>)}</section>{!filtered.length&&<p role="status">没有符合条件的资料，试试其他城市或关键词。</p>}<div className="editorial-pagination"><button disabled={current===1} onClick={()=>setPage(current-1)}>上一页</button><span>{current} / {pages}</span><button disabled={current===pages} onClick={()=>setPage(current+1)}>下一页</button></div></main>
}
