import React,{useEffect,useRef,useState} from 'react';
import collection from './data/editorial-places.json';
import mediaManifest from './data/editorial-media.json';
const reviewMode=import.meta.env.MODE==='editorial-review';
const dimensions=[['design','设计特色',35],['setting','环境景观',30],['access','到访便利',20],['evidence','资料支撑',15]];
const rank=n=>String(n).padStart(2,'0');
function Bars({record}){return <div className="ed-bars">{dimensions.map(([key,label,max])=><div className="ed-bar" key={key}><span>{label}</span><meter min="0" max={max} value={record.editorial.components[key]} aria-label={`${label} ${record.editorial.components[key]}/${max}`}/><b>{record.editorial.components[key]}<small>/{max}</small></b></div>)}</div>}
function Photo({record,onError,eager=false}){return <img src={record.media.src} alt={`${record.displayCity} · ${record.name} 来源实拍`} loading={eager?'eager':'lazy'} decoding="async" onError={()=>onError(record.id)}/>}
function Detail({record,close,onError}){
 const ref=useRef(null);useEffect(()=>{const node=ref.current;node.showModal();return()=>node.close()},[]);
 return <dialog ref={ref} className="ed-dialog" aria-labelledby="ed-detail-title" onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close()}}><button autoFocus className="ed-close" aria-label="关闭地点详情" onClick={close}>×</button><div className="ed-detail-photo"><Photo record={record} onError={onError} eager/></div><div className="ed-detail-body"><div className="ed-eyebrow">{record.province} / {record.displayCity} · {record.category}</div><h2 id="ed-detail-title">{record.name}</h2><p>{record.feature}</p><div className="ed-detail-score"><strong>{record.editorial.score}<small>/100</small></strong><span>编辑综合推荐分<small>基于公开资料，不是用户评分</small></span></div><Bars record={record}/><table className="ed-facts"><caption>地点与到访信息</caption><tbody><tr><th scope="row">具体位置</th><td>{record.address}</td></tr><tr><th scope="row">进入条件</th><td>{record.access}</td></tr><tr><th scope="row">资料日期</th><td>{record.publishedAt||'原文未注明'}{record.sourceAgeDays>730?' · 超过两年，当前状态需复核':''}</td></tr><tr><th scope="row">真实评价</th><td>暂无可核验用户评分；卫生、气味和排队未作评分。</td></tr><tr><th scope="row">照片来源</th><td>{record.media.author||'摄影者未单列'} · {record.media.licenseLabel}</td></tr></tbody></table><div className="ed-source-links"><a href={record.sourceUrl} target="_blank" rel="noopener noreferrer">原始地点资料 ↗</a><a href={record.mediaSourceUrl} target="_blank" rel="noopener noreferrer">原始图文 / 视频 ↗</a></div></div></dialog>
}
export default function EditorialPlaces(){return <ResearchEditorial/>}
function ResearchEditorial(){
 const [scope,setScope]=useState('top'),[layout,setLayout]=useState('cards'),[query,setQuery]=useState(''),[city,setCity]=useState(''),[sort,setSort]=useState('score'),[page,setPage]=useState(1),[selected,setSelected]=useState(null),[failed,setFailed]=useState([]);
 const records=collection.records.flatMap(r=>{const media=mediaManifest[r.id];return media&&!failed.includes(r.id)?[{...r,media}]:[]});
 const top=records.filter(r=>r.rank).sort((a,b)=>a.rank-b.rank),cities=[...new Set(records.map(r=>r.city))].sort((a,b)=>a.localeCompare(b,'zh'));
 const filtered=records.filter(r=>(scope!=='top'||r.rank)&&(!city||r.city===city)&&`${r.name} ${r.city} ${r.province} ${r.address} ${r.feature}`.includes(query.trim())).sort((a,b)=>{const value=r=>sort==='score'?r.editorial.score:r.editorial.components[sort];return value(b)-value(a)||(a.rank||999)-(b.rank||999)||a.id.localeCompare(b.id)});
 const pages=Math.max(1,Math.ceil(filtered.length/12)),current=Math.min(page,pages),visible=filtered.slice((current-1)*12,current*12),hero=top.find(r=>r.rank===2)||top[0];
 const change=(setter,value)=>{setter(value);setPage(1)},onError=id=>setFailed(prev=>prev.includes(id)?prev:[...prev,id]);
 useEffect(()=>{document.title='全国30城厕所推荐榜 · 必拉榜'},[]);
 useEffect(()=>{if(selected&&failed.includes(selected.id))setSelected(null)},[failed,selected]);
 return <main className="ed-page">{reviewMode&&<div className="ed-review-note">本地审阅版 · 真实来源照片仅供研究预览，本站展示授权待完成。此版本未公开发布。</div>}
 <section className="ed-hero" aria-labelledby="ed-title"><div className="ed-hero-copy"><div className="ed-eyebrow">● 必拉榜 · 城市目的地指南</div><h1 id="ed-title">全国 <em>30</em> 城<br/>厕所推荐榜<span>。</span></h1><p className="ed-lead">每座城，只推荐一处。<br/>从山野景观到街巷设计，看看你的城市排在哪里。</p><a className="ed-primary" href="#city-leaderboard">看完整榜单 <span>↓</span></a><div className="ed-hero-stats"><div><b>{top.length}<small>城</small></b><span>一城一厕推荐</span></div><div><b>{records.length}<small>处</small></b><span>特色地点资料</span></div><div><b>4<small>维</small></b><span>编辑评分依据</span></div></div></div>{hero?<button className="ed-hero-photo" aria-label={`查看${hero.name}照片与详情`} onClick={()=>setSelected(hero)}><Photo record={hero} onError={onError} eager/><span className="ed-hero-rank">NO.{rank(hero.rank)}<small>本期城市推荐</small></span><span className="ed-hero-caption"><span><small>{hero.province} / {hero.displayCity}</small><strong>{hero.name}</strong></span><b>{hero.editorial.score}<small>编辑推荐分</small></b></span></button>:<div className="ed-empty"><h2>有图榜单正在补齐素材</h2><p>图片暂时无法加载，请稍后重试。</p></div>}</section>
 <section className="ed-board" id="city-leaderboard" aria-labelledby="ed-board-title"><div className="ed-board-heading"><div><div className="ed-eyebrow">THE CITY TOP 30</div><h2 id="ed-board-title">30座城，30个好去处。</h2><p>综合推荐分满分100 · 每城最多一处 · 公开资料整理</p></div><div className="ed-view-switch" role="group" aria-label="榜单视图"><button aria-pressed={layout==='cards'} onClick={()=>setLayout('cards')}>▦ 看图选地点</button><button aria-pressed={layout==='table'} onClick={()=>setLayout('table')}>☷ 评分对比表</button></div></div>
 <div className="ed-score-key"><strong>综合分怎么来的？</strong>{dimensions.map(([key,label,max])=><span key={key}><i className={'ed-dot '+key}/>{label} <b>{max}%</b></span>)}<details><summary>评分说明</summary><p>设计、景观、便利为基于照片和事实的主观判断，资料分反映证据支持程度。这不是用户评价或亲身到访，不评价卫生、气味与排队。候选先按城市选一处，再取前30，相差1–2分不代表可测量的体验差距。整理于 {collection.asOf}，不是全国普查。</p></details></div>
 <div className="ed-filters"><div className="ed-scope" role="group" aria-label="推荐范围"><button aria-pressed={scope==='top'} onClick={()=>change(setScope,'top')}>全国30城榜</button><button aria-pressed={scope==='all'} onClick={()=>change(setScope,'all')}>全部有图 · {records.length}</button></div><input value={query} onChange={e=>change(setQuery,e.target.value)} aria-label="搜索地点" placeholder="搜索城市、景点、厕所名称"/><select value={city} onChange={e=>change(setCity,e.target.value)} aria-label="筛选城市"><option value="">全部城市</option>{cities.map(c=><option key={c}>{c}</option>)}</select><select value={sort} onChange={e=>change(setSort,e.target.value)} aria-label="排序维度"><option value="score">综合分优先</option>{dimensions.map(([key,label])=><option key={key} value={key}>{label}优先</option>)}</select></div>
 <div className="ed-results"><span>共 <b>{filtered.length}</b> 处 · 第 {current} / {pages} 页</span><span>实拍可看 · 城市可找 · 分项可比</span></div>
 {layout==='cards'?<div className="ed-cards">{visible.map(r=><article className="ed-card" key={r.id}><button className="ed-card-photo" onClick={()=>setSelected(r)} aria-label={`查看${r.name}照片与详情`}><Photo record={r} onError={onError}/><span className="ed-rank">{r.rank?'NO. '+rank(r.rank):'候选'}</span><span className="ed-city">{r.displayCity}</span><span className="ed-photo-open">查看照片与详情 ↗</span></button><div className="ed-card-body"><div className="ed-card-meta">{r.province} · {r.category}</div><div className="ed-card-title"><h3><button onClick={()=>setSelected(r)}>{r.name}</button></h3><div className="ed-total"><b>{r.editorial.score}</b><span>综合 / 100</span></div></div><p className="ed-feature">{r.feature}</p><p className="ed-location">⌖ {r.address}</p><Bars record={r}/><div className="ed-photo-credit">摄影：{r.media.author||"原文未单列"} · <a href={r.mediaSourceUrl} target="_blank" rel="noopener noreferrer">图片来源 ↗</a></div><div className="ed-card-footer"><span>编辑推荐 · 非用户评分</span><button onClick={()=>setSelected(r)}>到访提示 ↗</button></div></div></article>)}</div>:<div className="ed-table-scroll" tabIndex="0" role="region" aria-label="评分对比表，可横向滚动"><table className="ed-table"><caption>全国城市厕所推荐 · 分项评分对比</caption><thead><tr><th scope="col">排名</th><th scope="col">地点 / 城市</th><th scope="col" aria-sort={sort==='score'?'descending':'none'}><button onClick={()=>change(setSort,'score')}>综合分 ↓</button></th>{dimensions.map(([key,label,max])=><th scope="col" key={key} aria-sort={sort===key?'descending':'none'}><button onClick={()=>change(setSort,key)}>{label}<small>满分 {max}</small></button></th>)}<th scope="col">详情</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td className="ed-table-rank">{r.rank?rank(r.rank):'—'}</td><td><button className="ed-table-place" onClick={()=>setSelected(r)}><Photo record={r} onError={onError}/><span><b>{r.name}</b><small>{r.province} / {r.displayCity}</small></span></button></td><td><strong className="ed-table-total">{r.editorial.score}</strong></td>{dimensions.map(([key,label,max])=><td key={key}><div className="ed-table-bar"><b>{r.editorial.components[key]}</b><meter min="0" max={max} value={r.editorial.components[key]} aria-label={`${label} ${r.editorial.components[key]}/${max}`}/></div></td>)}<td><button className="ed-text-button" onClick={()=>setSelected(r)} aria-label={`查看${r.name}详情`}>查看 ↗</button></td></tr>)}</tbody></table></div>}
 {!filtered.length&&<div className="ed-empty" role="status"><h3>{records.length?'没有符合条件的地点':'公开展示素材正在核验'}</h3><p>{records.length?'换个城市或关键词试试。':'图片暂时无法加载，请稍后重试。'}</p></div>}<div className="ed-pagination"><button disabled={current===1} onClick={()=>setPage(current-1)}>← 上一页</button><span>{current} / {pages}</span><button disabled={current===pages} onClick={()=>setPage(current+1)}>下一页 →</button></div></section>
 {failed.length>0&&<p className="ed-load-note" role="status">{failed.length}处媒体暂时不可用，已从本次展示中移除。</p>}{selected&&<Detail record={selected} close={()=>setSelected(null)} onError={onError}/>}
 </main>
}
