import React,{useState,useRef,useEffect} from 'react';
import collection from './data/editorial-places.json';
import archive from './data/editorial-public-media.json';
import './public-editorial.css';
const axes=[['design','设计',35],['setting','景观',30],['access','到访',20],['evidence','证据',15]];
function Picture({photo}){
 const [failed,setFailed]=useState(false);
 return failed?<a className="pe-photo-fallback" href={photo.sourceUrl} target="_blank" rel="noopener noreferrer">照片暂未加载，查看作者原图 ↗</a>:<img src={photo.src} alt={`${photo.city} · ${photo.name}，拍摄于${photo.date.slice(0,10)}`} loading="lazy" onError={()=>setFailed(true)}/>;
}
function Facts({record,close}){
 const ref=useRef(null);
 useEffect(()=>{ref.current.showModal();return()=>ref.current?.close()},[]);
 return <dialog className="pe-dialog" ref={ref} onCancel={close} onClick={e=>e.target===e.currentTarget&&close()} aria-labelledby="pe-place-name"><button autoFocus className="pe-close" onClick={close} aria-label="关闭详情">×</button><small>{record.province} / {record.displayCity}</small><h2 id="pe-place-name">{record.name}</h2><p>{record.feature}</p><div className="pe-score"><b>{record.editorial.score}</b><span>编辑推荐分 / 100<br/>不是用户实测评分</span></div><dl><dt>具体位置</dt><dd>{record.address}</dd><dt>到访条件</dt><dd>{record.access}</dd><dt>资料日期</dt><dd>{record.publishedAt||'来源未注明'}；不代表当前状态已经实地复核。</dd></dl><div className="pe-axis">{axes.map(([key,label,max])=><div key={key}><span>{label} {record.editorial.components[key]}/{max}</span><meter min="0" max={max} value={record.editorial.components[key]}/><p>{record.editorial.rationale[key]}</p></div>)}</div><p className="pe-note">本页整理地点事实与编辑判断。该地点的实拍请前往原始来源查看；本站没有取得其照片转载许可。</p><div className="pe-links"><a target="_blank" rel="noopener noreferrer" href={record.mediaSourceUrl||record.sourceUrl}>查看来源实拍 / 视频 ↗</a><a target="_blank" rel="noopener noreferrer" href={record.sourceUrl}>地点原始资料 ↗</a></div>{record.supplementalEvidence?.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer">补充证据：{s.publisher} ↗</a><br/>{s.note}</p>)}</dialog>;
}
export default function PublicEditorial(){
 const [scope,setScope]=useState('top'),[query,setQuery]=useState(''),[sort,setSort]=useState('score'),[selected,setSelected]=useState(null),[playing,setPlaying]=useState({});
 const rows=collection.records.filter(r=>(scope==='all'||r.rank)&&`${r.name} ${r.city} ${r.displayCity} ${r.province} ${r.address}`.includes(query.trim())).sort((a,b)=>(sort==='score'?b.editorial.score-a.editorial.score:b.editorial.components[sort]-a.editorial.components[sort])||(a.rank||999)-(b.rank||999));
 const hero=archive.photos[0];
 return <main className="pe-page"><section className="pe-hero"><div><div className="pe-kicker">必拉榜 / 城市与公共空间</div><h1>全国 <em>30</em> 城，<br/>谁家的厕所<br/>更值得看？</h1><p>山野、海岸与街巷里的公共空间。<br/>看真实影像，比设计与景观，也看清到访条件。</p><div className="pe-links"><a className="pe-primary" href="#pe-ranking">看30城资料榜 ↓</a><a href="#pe-archive">先看实拍档案 ↗</a></div><div className="pe-stats"><span><b>30</b>城市榜单</span><span><b>{collection.records.length}</b>地点资料</span><span><b>{archive.photos.length}</b>实拍档案</span></div></div><figure><Picture photo={hero}/><figcaption><span>影像档案 · {hero.date.slice(0,4)}</span><strong>{hero.city} / {hero.name}</strong><small>照片记录，不代表当前到访推荐</small></figcaption></figure></section>
 <section id="pe-archive"><div className="pe-heading"><div><div className="pe-kicker">PHOTO ARCHIVE / 实拍可追溯</div><h2>从一张照片，认识一座城。</h2></div><p>公开许可实拍 · 保留拍摄日期与署名<br/>历史照片不等于现状，未定位条目不收入这里。</p></div><div className="pe-gallery">{archive.photos.map(p=><article key={p.id}><Picture photo={p}/><div><small>{p.province} / {p.city} · {p.date.slice(0,10)}</small><h3>{p.name}</h3><p>{p.note}</p><footer>摄影：{p.author} · <a href={p.licenseUrl} target="_blank" rel="noopener noreferrer">{p.license}</a><br/>{p.modifications}；衍生图片遵循原许可。<br/><a href={p.sourceUrl} target="_blank" rel="noopener noreferrer">原图、作者与许可 ↗</a></footer></div></article>)}</div></section>
 <section id="pe-ranking"><div className="pe-heading"><div><div className="pe-kicker">CITY TOP 30 / 一城一厕</div><h2>你的城市，排在哪里？</h2></div><p>编辑推荐分 · 非用户评价<br/>整理于 {collection.asOf}，部分地点当前状态待复核。</p></div><div className="pe-legend">{axes.map(([key,label,max])=><span key={key}>{label}<b>{max}%</b></span>)}<details><summary>这些分数意味着什么？</summary><p>设计、景观、到访为公开资料下的主观判断；证据分反映资料支持。没有实测卫生、气味、排队；相差1–2分不代表可测量的体验差距。每城先选一处，再取前30。图片档案与这张资料榜分别标识，不将别处照片配给榜上地点。</p></details></div><div className="pe-filters"><div><button aria-pressed={scope==='top'} onClick={()=>setScope('top')}>30城榜</button><button aria-pressed={scope==='all'} onClick={()=>setScope('all')}>全部资料 {collection.records.length}</button></div><input aria-label="搜索榜单" placeholder="搜索城市、地点、景点" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="榜单排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="score">综合分优先</option>{axes.map(([key,label])=><option key={key} value={key}>{label}分优先</option>)}</select><span>{rows.length}处</span></div><p className="pe-note">榜单地点的实拍入口保留在每条资料中；本站可展示的照片单列为上方影像档案。</p><div className="pe-table-wrap" tabIndex="0" role="region" aria-label="城市评分对比表，可横向滚动"><table><caption>全国城市厕所资料与编辑分项对比</caption><thead><tr><th>排名</th><th>城市 / 地点</th><th>综合</th>{axes.map(([k,label,max])=><th key={k}>{label}<small>/{max}</small></th>)}<th>了解这处</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="pe-rank">{r.rank?String(r.rank).padStart(2,'0'):'—'}</td><td><span className="pe-city">{r.displayCity}</span><button className="pe-name" onClick={()=>setSelected(r)}>{r.name}</button><small>{r.category}</small></td><td className="pe-total">{r.editorial.score}</td>{axes.map(([key,label,max])=><td key={key}><b>{r.editorial.components[key]}</b><meter min="0" max={max} value={r.editorial.components[key]} aria-label={`${label} ${r.editorial.components[key]}/${max}`}/></td>)}<td><button onClick={()=>setSelected(r)}>位置与依据</button><a href={r.mediaSourceUrl||r.sourceUrl} target="_blank" rel="noopener noreferrer">看来源实拍 ↗</a></td></tr>)}</tbody></table></div>{!rows.length&&<p role="status">没有匹配结果，换个城市或名称试试。</p>}</section>
 <section><div className="pe-heading"><div><div className="pe-kicker">DESIGN FILMS / 项目观察</div><h2>厕所，也可以成为话题。</h2></div><p>项目片含品牌宣传，不作为使用体验评分。<br/>点击后由腾讯视频播放，可能包含广告。</p></div><div className="pe-films">{archive.videos.map((v,i)=><article key={v.id}>{playing[v.id]?<iframe title={v.title} src={v.embedUrl} allow="fullscreen" allowFullScreen/>:<button className="pe-film-play" onClick={()=>setPlaying(p=>({...p,[v.id]:true}))}><span>FILM / 0{i+1}</span><strong>{v.title}</strong><b>▶ 点击加载官方视频</b></button>}<div><h3>{v.title}</h3><p>{v.note}</p><footer>{v.publisher} · {v.date}<br/><a href={v.embedUrl} target="_blank" rel="noopener noreferrer">播放器打不开？在原平台观看 ↗</a> · <a href={v.sourceUrl} target="_blank" rel="noopener noreferrer">项目来源 ↗</a></footer></div></article>)}</div></section><aside className="pe-contribute"><h2>比榜单更懂你的城市？</h2><p>提供一处真实地点、你拍的照片和具体入口。好地方，值得被更多人找到。</p><a className="pe-primary" href="/share">分享你的发现 ↗</a></aside>{selected&&<Facts record={selected} close={()=>setSelected(null)}/>}</main>;
}
