import MapPicker from './MapPicker.jsx';
import Select from './Select.jsx';
import React,{useState,useEffect,useRef} from 'react';
import RegionPicker from './RegionPicker.jsx';
import DuplicateNotice from './DuplicateNotice.jsx';
import SubmissionPreview from './SubmissionPreview.jsx';
import {saveReceipt,readDraftPhotos,writeDraftPhotos,deleteDraftPhotos} from './local-contributions.js';
import {regionLabel} from './regions.js';
import {validatePlace,photoKinds,today} from './place-schema.js';
const initial={template:'visited',name:'',regionId:'',address:'',description:'',locationMode:'text',lat:'',lng:'',landmark:'',directions:'',date:'',checkedAt:today(),sourceUrl:'',publisher:'',hours:'',fee:'',customRegion:'',wheelchair:'unknown',babycare:'unknown',paper:'unknown',water:'unknown',consent:false};
export default function SubmissionWizard({config,user,notify,api,Verification,onDone,onReceipt,places=[]}){
 const key='bilabang-draft-v2-'+(user?.id||'guest');
 const requestId=useRef(null);
 const errorRef=useRef(null);

 const [b,setB]=useState(()=>{try{return {...initial,...JSON.parse(localStorage.getItem(key)||'{}')};}catch{return initial;}}),[step,setStep]=useState(0),[photos,setPhotos]=useState([]),[errors,setErrors]=useState({}),[busy,setBusy]=useState(false),[verification,setVerification]=useState(''),[vkey,setVkey]=useState(0),[receipt,setReceipt]=useState(null),[storageError,setStorageError]=useState(''),[photoError,setPhotoError]=useState(''),[photoReady,setPhotoReady]=useState(false);
 if(!requestId.current)requestId.current=b.__requestId||crypto.randomUUID();
 useEffect(()=>{errorRef.current?.focus();},[errors]);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify({...b,__requestId:requestId.current}));setStorageError('');}catch{setStorageError('浏览器未允许保存草稿，关闭页面后文字可能丢失。');}},[b,key]);
 useEffect(()=>{let active=true;readDraftPhotos(key).then(saved=>{if(active&&Array.isArray(saved))setPhotos(saved.filter(p=>p.file instanceof Blob).map(p=>({...p,url:URL.createObjectURL(p.file)})));}).catch(()=>{if(active)setPhotoError('浏览器未允许保存照片，关闭后需重新选择。');}).finally(()=>{if(active)setPhotoReady(true);});return()=>{active=false;};},[key]);
 useEffect(()=>{if(!photoReady||receipt)return;writeDraftPhotos(key,photos).then(()=>setPhotoError('')).catch(()=>setPhotoError('照片草稿未保存成功，关闭后需重新选择。'));},[photos,photoReady,receipt,key]);
 const urls=useRef([]);useEffect(()=>{urls.current.push(...photos.map(p=>p.url));},[photos]);useEffect(()=>()=>new Set(urls.current).forEach(u=>URL.revokeObjectURL(u)),[]);
 const change=(k,v)=>setB(p=>({...p,[k]:v}));
 function field(k,label,type='text',required=false){return <label className="wizard-field" key={k}>{label} <small>{required?'必填':'选填'}</small>{type==='textarea'?<textarea value={b[k]} onChange={e=>change(k,e.target.value)} maxLength={2000}/>:<input type={type} value={b[k]} onChange={e=>change(k,e.target.value)} max={type==='date'?today():undefined} maxLength={k==='description'?2000:200}/>} {errors[k]&&<span className="field-error">{errors[k]}</span>}</label>;}
 function next(){const all=validatePlace(b,photos);const keys=step===0?['template']:step===1?['name','regionId','address','description','locationMode','lat','lng','landmark','directions','date','customRegion']:['sourceUrl','publisher','checkedAt','photos'];const relevant=Object.fromEntries(Object.entries(all).filter(([k])=>keys.includes(k)));setErrors(relevant);if(!Object.keys(relevant).length)setStep(step+1);}
 async function submit(publish){const e=validatePlace(b,photos);setErrors(e);if(Object.keys(e).length)return;setBusy(true);try{const f=new FormData();f.set('payload',JSON.stringify({...b,publish,requestId:requestId.current}));f.set('photoMetadata',JSON.stringify(photos.map(({file,url,...p})=>p)));f.set('verification',verification);photos.forEach(p=>f.append('photos',p.file));const result=await api('/submissions',{method:'POST',body:f});setReceipt(result);try{saveReceipt(result,b.name);}catch{setStorageError('投稿成功，但本机回执未保存，请复制回执。');}deleteDraftPhotos(key).catch(()=>{});try{localStorage.removeItem(key);}catch{}onDone?.();notify(result.status==='approved'?'地点已审核发布':'已提交审核');}catch(e){setErrors(e.fields&&typeof e.fields==='object'?{...e.fields,submit:e.message}:{submit:e.message});if(e.message.includes('验证')){setVerification('');setVkey(v=>v+1);}}finally{setBusy(false);}}
 if(receipt)return <div className="notice"><h3>已{receipt.status==='approved'?'发布':'提交审核'}</h3><p>请保存回执，用于查询审核进度：</p><code style={{overflowWrap:'anywhere'}}>{receipt.receipt}</code><p>投稿审核通过后公开；资料收录不会自动产生评分。</p>{storageError&&<p>{storageError}</p>}<div className="wizard-actions"><button className="primary" onClick={()=>navigator.clipboard.writeText(receipt.receipt).then(()=>notify("回执已复制")).catch(()=>notify("请手动选择并复制回执"))}>复制回执</button><button className="outline" onClick={()=>onReceipt?.(receipt.receipt)}>查询投稿进度</button></div></div>;
 return <div className="submission-wizard"><div className="wizard-steps">{['选择模板','地点与找路','照片与资料','预览提交'].map((s,i)=><span key={s} aria-current={i===step?'step':undefined} className={i===step?'current':''}>{i+1}. {s}</span>)}</div><p className="muted">文字与照片草稿保存在本机，可在此浏览器继续填写；请勿在共用设备保留私人草稿。</p>
 {photoError&&<p role="status" className="notice">{photoError}</p>}{storageError&&<p role="status" className="notice">{storageError}</p>}{Object.keys(errors).length>0&&<div role="alert" ref={errorRef} tabIndex={-1} className="notice">{Object.values(errors).map((s,i)=><p key={i}>{s}</p>)}</div>}
 {step===0&&<div className="template-options">{[['visited','实地分享','我亲自到访，提供日期与实拍照片。'],['source','公开资料收录','整理公开信息，保留作者与原文，不虚构到访体验。']].map(([v,title,desc])=><label key={v}><input type="radio" name="template" checked={b.template===v} onChange={()=>change('template',v)}/><strong>{title}</strong><p>{desc}</p></label>)}</div>}
 {(step===1||step===3)&&<DuplicateNotice draft={b} places={places}/>}
 {step===1&&<><div className="form-grid">{field('name','厕所名称','text',true)}<div className="wizard-field">所在地区 · 必填<RegionPicker creation value={b.regionId} onChange={v=>change('regionId',v)}/>{!b.regionId&&<small>至少选择已知上级；区县不明确时不猜测。</small>}</div>{field('customRegion','目录中未覆盖的城市 / 区县')}{field('address','详细位置 / 入口 / 楼层','text',true)}</div>{field('description','这处厕所的特点','textarea',true)}<MapPicker value={b} config={config} onChange={v=>setB(p=>({...p,...v}))}/><label className="wizard-field">定位方式 · 必填<Select value={b.locationMode} onChange={e=>change('locationMode',e.target.value)}><option value="text">暂无地图点位，用文字找路</option><option value="reference">只有附近地标坐标</option><option value="precise">已确认厕所精确坐标</option></Select></label>{b.locationMode!=='text'&&<><p className="notice">请使用 WGS84 坐标。国内地图坐标不能直接混用；参考点不会显示为厕所入口。</p><div className="form-grid">{field('lat','纬度','number',true)}{field('lng','经度','number',true)}</div></>}{b.locationMode==='reference'&&field('landmark','参考地标名称','text',true)}{field('directions','如何找到：从哪里出发、转弯、入口标志（每行一步）','textarea',b.template==='visited'&&b.locationMode!=='precise')}{b.template==='source'&&<small>来源没有提供路线时可留空，将显示“入口路线待补充”。</small>}{b.template==='visited'&&field('date','到访日期','date',true)}<div className="form-grid">{field('hours','开放时间（不详留空）')}{field('fee','费用 / 门票要求（不详留空）')}</div><h3>设施信息 · 选填</h3><div className="form-grid">{[['wheelchair','无障碍设施'],['babycare','母婴 / 亲子空间'],['paper','卫生纸'],['water','洗手水源']].map(([k,t])=><label className="wizard-field" key={k}>{t}<Select value={b[k]||'unknown'} onChange={e=>change(k,e.target.value)}><option value="unknown">不清楚</option><option value="yes">有</option><option value="no">没有</option></Select></label>)}</div></>}
 {step===2&&<>{b.template==='source'&&<>{field('sourceUrl','原帖 / 原文链接','url',true)}{field('publisher','作者或发布者原名','text',true)}{field('checkedAt','资料核查日期','date',true)}</>}<h3>照片 {b.template==='visited'?'· 至少一张':'· 可暂缺'}</h3><p>最多 6 张，每张 8 MB。勿拍摄使用者、私密部位；每张图片单独注明用途与权利。</p><input type="file" aria-label="添加照片" disabled={!photoReady} accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{const files=Array.from(e.target.files);if(photos.length+files.length>6||files.some(f=>f.size>8*1024*1024)){setErrors({photos:'最多6张，每张不超过8MB'});return;}setPhotos(p=>[...p,...files.map(file=>({file,url:URL.createObjectURL(file),kind:'exterior',caption:'',rights:'own',author:'',sourceUrl:'',license:''}))]);e.target.value='';}}/>{photos.map((p,i)=><div className="photo-editor" key={p.url}><img src={p.url} alt={`待上传照片${i+1}`}/><div><strong>{i===0?'封面照片':`照片 ${i+1}`}</strong>{[['kind',photoKinds],['rights',{own:'本人拍摄',authorized:'已获作者授权',licensed:'开放许可'}]].map(([k,opts])=><Select key={k} aria-label={k==='kind'?'照片用途':'图片权利'} value={p[k]} onChange={e=>setPhotos(ps=>ps.map((a,n)=>n===i?{...a,[k]:e.target.value}:a))}>{Object.entries(opts).map(([v,t])=><option key={v} value={v}>{t}</option>)}</Select>)}{['caption',...(p.rights==='own'?[]:['author','sourceUrl','license'])].map(k=><input key={k} aria-label={{caption:'照片说明',author:'图片作者',sourceUrl:'原图链接',license:'授权或许可说明'}[k]} placeholder={{caption:'照片说明 / 对应找路步骤（必填）',author:'图片作者（必填）',sourceUrl:'原图链接（必填）',license:'授权或许可名称及证据（必填）'}[k]} value={p[k]} onChange={e=>setPhotos(ps=>ps.map((a,n)=>n===i?{...a,[k]:e.target.value}:a))}/>)}<button type="button" disabled={!i} onClick={()=>setPhotos(ps=>[ps[i],...ps.filter((_,n)=>n!==i)])}>设为封面</button><button type="button" onClick={()=>setPhotos(ps=>ps.filter((_,n)=>n!==i))}>移除</button></div></div>)}</>}
 {step===3&&<><SubmissionPreview place={b} photos={photos} onEdit={s=>{setErrors({});setStep(s);}}/><label className="consent"><input type="checkbox" checked={b.consent} onChange={e=>change('consent',e.target.checked)}/>我确认信息如实填写，图片自有或已获使用许可，同意审核后公开。</label><Verification key={vkey} config={config} onVerified={setVerification} skip={!!user}/><button type="button" onClick={()=>{setVerification('');setVkey(v=>v+1);}}>重新验证（草稿保留）</button></>}
 <div className="wizard-actions"><button type="button" disabled={busy||step===0} onClick={()=>{setErrors({});setStep(step-1);}}>上一步</button>{step<3?<button type="button" className="primary" disabled={!photoReady} onClick={next}>下一步</button>:<><button type="button" className="primary" disabled={busy||!photoReady||!config.writeEnabled||(!user&&!verification)} onClick={()=>submit(false)}>{busy?'提交中…':'提交审核'}</button>{user?.role==='admin'&&<button type="button" disabled={busy||!photoReady||!config.writeEnabled||!!b.customRegion} onClick={()=>submit(true)}>确认审核并发布</button>}</>}</div><button type="button" disabled={busy||!photoReady} onClick={()=>{requestId.current=crypto.randomUUID();setB({...initial});setPhotos([]);deleteDraftPhotos(key).catch(()=>{});setStep(0);setErrors({});try{localStorage.removeItem(key);}catch{}}}>清空本机草稿</button></div>;
}
